{{- if and .Values.workers.enabled .Values.workers.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workers.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "deriv-apps.labels" . | nindent 4 }}
  {{- with .Values.workers.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . | quote }}
  {{- end }}
{{- end }}
