apiVersion: v2
name: eks-monitoring
description: Grafana Loki stack — logs from deriv-dev workloads
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: loki
    version: "6.30.1"
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: "6.17.0"
    repository: https://grafana.github.io/helm-charts
  - name: grafana
    version: "9.2.10"
    repository: https://grafana.github.io/helm-charts
