ALTER TABLE "Workflow"
ADD COLUMN IF NOT EXISTS "riskCapital" DOUBLE PRECISION DEFAULT 5;

ALTER TABLE "Workflow"
ADD COLUMN IF NOT EXISTS "mmCycleTrades" INTEGER DEFAULT 10;

ALTER TABLE "Workflow"
ADD COLUMN IF NOT EXISTS "mmTargetWins" INTEGER DEFAULT 6;

ALTER TABLE "Workflow"
ADD COLUMN IF NOT EXISTS "mmPayout" DOUBLE PRECISION DEFAULT 1.95;

ALTER TABLE "Workflow"
ADD COLUMN IF NOT EXISTS "accountCurrency" TEXT DEFAULT 'USD';

ALTER TABLE "Workflow"
ADD COLUMN IF NOT EXISTS "contractStrategy" TEXT DEFAULT 'rise_fall';

ALTER TABLE "Workflow"
ADD COLUMN IF NOT EXISTS "durationTicks" INTEGER DEFAULT 2;
