global:
  environment: dev
  namespaceOverride: deriv-dev
  imageRegistry: docker.io
  security:
    allowInsecureImages: true

namespace:
  create: false
  name: deriv-dev

secrets:
  existingSecret: deriv-platform-app-secrets

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 16.4.0-debian-12-r14
  auth:
    username: deriv
    database: deriv
    existingSecret: deriv-platform-app-secrets
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: POSTGRES_PASSWORD
  primary:
    persistence:
      enabled: true
      size: 8Gi
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
      tag: 12-debian-12-r30
  metrics:
    enabled: false
