global:
  environment: dev
  namespaceOverride: deriv-dev
  imageRegistry: docker.io
  security:
    allowInsecureImages: true

namespace:
  create: false
  name: deriv-dev

# Bitnami service name when release is deriv-kafka (release name contains chart name)
kafkaServiceHost: deriv-kafka

kafkaTopics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/kafka
    tag: 3.8.0-debian-12-r5
  topics:
    - name: workflow.scheduled
      partitions: 3
    - name: workflow.execute
      partitions: 3
    - name: workflow.run.status
      partitions: 3

kafka:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/kafka
    tag: 3.8.0-debian-12-r5
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
      tag: 12-debian-12-r30
  kraft:
    enabled: true
  controller:
    replicaCount: 1
  broker:
    replicaCount: 1
  listeners:
    client:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
  metrics:
    jmx:
      enabled: false
