global:
  environment: dev

namespace:
  name: deriv-dev

image:
  registry: ""
  tag: latest

backend:
  replicaCount: 1

workers:
  planner:
    replicaCount: 1
  executor:
    replicaCount: 1
  env:
    SAGEMAKER_EMBEDDING_ENDPOINT: deriv-ai-bot-dev-embed
    S3_VECTORS_BUCKET_NAME: deriv-ai-bot-dev-rag-vectors
    S3_VECTORS_INDEX_NAME: trade-embeddings

frontend:
  enabled: true
  env:
    NEXT_PUBLIC_BOT_BASE_URL: "https://api.testenvlab.shop"
