global:
  environment: dev

namespace:
  name: deriv-dev

# Upstream Services from deriv-apps release
backends:
  appsRelease: deriv-apps
  backend:
    enabled: true
    serviceName: deriv-apps-backend
    port: 8000
  frontend:
    enabled: false
    serviceName: deriv-apps-frontend
    port: 3000

ingress:
  enabled: false
  className: alb
  certificateArns: ""
  hosts:
    app: app.example.com
    api: api.example.com
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
