-- AlterTable
ALTER TABLE "Workflow" ADD COLUMN IF NOT EXISTS "riskCapital" DOUBLE PRECISION NOT NULL DEFAULT 5;
ALTER TABLE "Workflow" ADD COLUMN IF NOT EXISTS "mmCycleTrades" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Workflow" ADD COLUMN IF NOT EXISTS "mmTargetWins" INTEGER NOT NULL DEFAULT 6;
ALTER TABLE "Workflow" ADD COLUMN IF NOT EXISTS "mmPayout" DOUBLE PRECISION NOT NULL DEFAULT 1.95;
ALTER TABLE "Workflow" ADD COLUMN IF NOT EXISTS "accountCurrency" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "Workflow" ADD COLUMN IF NOT EXISTS "contractStrategy" TEXT NOT NULL DEFAULT 'rise_fall';
ALTER TABLE "Workflow" ADD COLUMN IF NOT EXISTS "durationTicks" INTEGER NOT NULL DEFAULT 2;
